

data = [ { "ID":12,
          "Name":"Jake",
          "Gender": "Male",
          "Age":30,
          "Ethnicity":"Caucasian",
          "Keywords":["break up", "depressed","debt"],
          "Location": { "Lat":40.6782, "Lon":-73.9442 },
         },
        { "ID":23,
          "Name":"Amy",
          "Gender": "Female",
          "Age":30,
          "Ethnicity":"Latino",
          "Keywords":["break up", "depressed","anxiety"],
          "Location": { "Lat":40.6782, "Lon":-73.9442 },
         },
        { "ID":33,
          "Name":"Charles",
          "Gender": "Male",
          "Age":30,
          "Ethnicity":"Italian",
          "Keywords":["broke","anxiety"],
          "Location": { "Lat":50.7061, "Lon":73.9442 },
         },
        { "ID":43,
          "Name":"Rosa",
          "Gender": "Female",
          "Age":30,
          "Ethnicity":"Latino",
          "Keywords":["broke","anxiety"],
          "Location": { "Lat":50.7061, "Lon":73.9442 },
         },
        { "ID":38,
          "Name":"Raymond Holt",
          "Gender": "Male",
          "Age":40,
          "Ethnicity":"Latino",
          "Keywords":["lonely","anxiety"],
          "Location": { "Lat":50.7061, "Lon":73.9442 },
         },
        { "ID":11,
          "Name":"Jessy",
          "Gender": "Female",
          "Age":18,
          "Ethnicity":"Mexican",
          "Keywords":["broke","lonely"],
          "Location": { "Lat":55.7061, "Lon":-2.290387},
         },
        { "ID":15,
          "Name":"Arthur",
          "Gender": "Male",
          "Age":20,
          "Ethnicity":"Jewish",
          "Keywords":["alcoholic","obsession"],
          "Location": { "Lat":52.741280, "Lon":-0.882582},
         },
        { "ID":16,
          "Name":"Jacob",
          "Gender": "Male",
          "Age":22,
          "Ethnicity":"Irish",
          "Keywords":["lonliness","broke"],
          "Location": { "Lat":59.741280, "Lon":-0.982582},
         },
       { "ID":21,
          "Name":"Evie",
          "Gender": "Female",
          "Age":31,
          "Ethnicity":"French",
          "Keywords":["depressed",""],
          "Location": { "Lat":52.741280, "Lon":-0.882582},
         },
        { "ID":30,
          "Name":"Alex",
          "Gender": "Male",
          "Age":31,
          "Ethnicity":"French",
          "Keywords":["depressed","family"],
          "Location": { "Lat":32.741280, "Lon":-20.232394},
         }
        
        
        
      ]
        
  